### ISSUE TITLE
Other versions

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ThexXTURBOXx/balkons-weaponmod#2]
I am planning to port the mod to other versions as well.
This is my current plan:
 - [x] 1.20.1
 - [x] 1.19.2
 - [x] 1.11.2
 - [x] 1.10.2
 - [x] 1.9.4
 - [x] 1.8.9
 - [x] 1.7.10

If you have any more version suggestions, feel free to request them here!

**Comment by Danmccool** [comment]
i Have A Suggestion its For 1.20.1

**Comment by Danmccool** [comment]
@ThexXTURBOXx

**Comment by xJon** [comment]
@ThexXTURBOXx What's the difference between the latest 1.12.2 Reforged release and this 1.12.2 release?

**Comment by ThexXTURBOXx** [comment]
@Danmccool I'll add it to the list! Shouldn't be too difficult :)

**Comment by Danmccool** [comment]
Thanks @ThexXTURBOXx

**Comment by ThexXTURBOXx** [comment]
@xJon Reforged was a completely new mod, which aimed to bring back the feeling of Balkon's WeaponMod. Hence, it did not contain exactly the same weapons and features.

However, this now is a direct port of Balkon's WeaponMod. Only very tiny changes were introduced (mildly noticeable).
For this reason, Reforged and BWM: Legacy are sadly also not interchangeable (due to having different mod IDs)

**Comment by xJon** [comment]
@ThexXTURBOXx So is BWM: Legacy a new rewrite, and its 1.12.2 version does not have overlapping code with Reforged?

**Comment by ThexXTURBOXx** [comment]
@xJon "Rewrite" is probably not the right word for it - "port" of Balkon's WeaponMod with tiny changes seems to be fitting.
But yes, the 1.12.2 version of BWM: Legacy does not have overlapping code with Reforged.
I would suggest anyone to migrate from Reforged to BWM: Legacy. Creators of already existing modpacks on the other hand should probably just include both mods at the same time such that users don't lose their already-crafted weapons

**Comment by Danmccool** [comment]
@ThexXTURBOXx When will you release the 1.20.1 version?

**Comment by ThexXTURBOXx** [comment]
@Danmccool Together with the next release of BWM: Legacy, which will be within the next one to two weeks.
If you want to try it out earlier than that, you can always build it yourself :)

**Comment by Danmccool** [comment]
@ThexXTURBOXx When will you release the 1.20.1 version?

**Comment by Danmccool** [comment]
@ThexXTURBOXx i am trying to build the 1.20.1 version and its stuck on :access transforming minecraft

Never Mind It Just Took 10m

**Comment by Danmccool** [comment]
@ThexXTURBOXx  How Do You Build The Mod?

**Comment by ThexXTURBOXx** [comment]
> How Do You Build The Mod?

Just clone the git repository and execute `./gradlew build`. The mod jar that you want is then located in `<platform>/build/libs`.
Replace `<platform>` by the mod loader you want the mod for.
For versions < 1.16, there is only Forge support and hence the mod is just located under `build/libs`

**Comment by ThexXTURBOXx** [comment]
All the versions on the list are done now! I will now need to test every version as far as possible and then I will publish the next version (if needed after some bugfixes of course!)
