### ISSUE TITLE
1.21 Visual Enhancement to look modern. 

### ISSUE THREAD

**Issue by makumaku1974** [ThexXTURBOXx/balkons-weaponmod#28]
I don't think ill do everything but i've already set for an example already with the battle axe since everything looks too old.  1.7.10 was my first experience with this mod and i kinda want to upgrade it a bit. Anyone is free to contribute textures to only this area.

![Screenshot 2024-06-24 200230](https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy/assets/129804277/4e42bd75-73c6-4366-915c-4eb4bb8ed08a)

**Comment by ThexXTURBOXx** [comment]
I'd like to keep the old textures in the base mod, but I am more than happy to share links to custom resource packs on the CurseForge, Modrinth and GitHub pages :)

**Comment by makumaku1974** [comment]
Thaanks. I would link my sources once it is finished.

**Comment by ThexXTURBOXx** [comment]
Perfect, thank you very much :)
Just keep me updated and I will link your resource pack together with #6

**Comment by makumaku1974** [comment]
![2024-06-25_18 57 22](https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy/assets/129804277/1ef03b0a-12a7-4c6e-b7fe-6f46061decbd)

I manage to create a resource pack and still testing out.

**Comment by ThexXTURBOXx** [comment]
Will close this for now :)
If you are finished at some point and want me to link it [here](https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy?tab=readme-ov-file#resource-pack-patches), just give me a heads up!

**Comment by makumaku1974** [comment]
> Will close this for now :) If you are finished at some point and want me to link it [here](https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy?tab=readme-ov-file#resource-pack-patches), just give me a heads up!

Thanks for notifying me. But right now ill be busy testing other mods so it'll be sooner or later.

**Comment by makumaku1974** [comment]
i'll be changing the knifes now.
