### ISSUE TITLE
Blocking Improvements

### ISSUE THREAD

**Issue by IcarussOne** [ThexXTURBOXx/balkons-weaponmod#32]
It's neat that you can block with certain weapons like battleaxes and katanas but I feel like with the current implementation, you can have an infinite shield, at least on the 1.12.2 verison.

- Durability should be taken when you manage to block damage like shields do.
- A different block sound would be nice for the weapons, you could take the unused zombie iron door attack and higher pitch it maybe.
- Could change the mechanic to be similar to pre-1.9 where only 50% of damage is negated. If done this way durability does not need to be taken like shields do.

**Comment by ThexXTURBOXx** [comment]
> you can have an infinite shield

Are you sure? I was of the impression that it was only a visual.
If it really works and deflects damage, then indeed, your suggestions make sense :)

**Comment by IcarussOne** [comment]
> > you can have an infinite shield
> 
> Are you sure? I was of the impression that it was only a visual. If it really works and deflects damage, then indeed, your suggestions make sense :)

Yes, I tested it again without any mods and it still was blocking.

https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy/assets/135455255/c994b273-d6ad-437b-b1bd-4a6d62e69c7f

**Comment by ThexXTURBOXx** [comment]
Interesting. Yes, in that case, some nerfing needs to take place. Just wondering: Which version is that? Probably 1.12.2 or something like that?

**Comment by IcarussOne** [comment]
Indeed, 1.12.2 is the version I was primarily using! :)

**Comment by ThexXTURBOXx** [comment]
Perfect, thanks for the feedback :)
In case you are wondering how I found out: It was not magic - that's just the most popular version before the new textures ;)
