### ISSUE TITLE
1.21 Crashma Game from Halberd by Right Clicking....

### ISSUE THREAD

**Issue by makumaku1974** [ThexXTURBOXx/balkons-weaponmod#35]
I totally forgot how halberd used to be in 1.7.10 but im using 1.21 and yeah it crashma game.

What happened next is that it disconnects me and crashes after. 

Here's the Log and Crash Report:
[crash-2024-06-27_14.57.04-server.txt](https://github.com/user-attachments/files/16009407/crash-2024-06-27_14.57.04-server.txt)
[latest.log](https://github.com/user-attachments/files/16009410/latest.log)

**Comment by ThexXTURBOXx** [comment]
This is already fixed - just needs the next version to be released :)
