### ISSUE TITLE
1.21 Weapon Bug

### ISSUE THREAD

**Issue by makumaku1974** [ThexXTURBOXx/balkons-weaponmod#36]

**Comment by ThexXTURBOXx** [comment]
Could you maybe describe the bug?

**Comment by makumaku1974** [comment]
List: Musket, Pistol, Blunderbuss, Hand Mortar, Crossbow can block Skeleton attacks when reloading.

**Comment by ThexXTURBOXx** [comment]
Okay, thanks! I will close this as a duplicate of #32 then
