### ISSUE TITLE
BWMGetsReforged

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ThexXTURBOXx/balkons-weaponmod#41]
Currently don't have the time, but maybe at some point I will make a resource pack "BWMGetsReforged", which overrides BWM: Legacy's oldschool textures with [Reforged's textures](https://github.com/ThexXTURBOXx/Reforged/tree/1.12/src/main/resources/assets/reforged/textures/items).
The reverse of it (ReforgedGetsBalkoned) still exists and is still around: https://femtopedia.de/RGB/

**Comment by ThexXTURBOXx** [comment]
Done: https://modrinth.com/resourcepack/balkons-gets-reforged
Just needs to be added to the README(s)!

**Comment by ThexXTURBOXx** [comment]
@Squeekblach Would you be able to help me here again, please? :)
I would like to have the following textures as Netherite versions:
 - https://github.com/ThexXTURBOXx/Reforged/blob/1.12/src/main/resources/assets/reforged/textures/items/battleaxe_diamond.png
 - https://github.com/ThexXTURBOXx/Reforged/blob/1.12/src/main/resources/assets/reforged/textures/items/boomerang_diamond.png
 - https://github.com/ThexXTURBOXx/Reforged/blob/1.12/src/main/resources/assets/reforged/textures/items/katana_diamond.png
 - https://github.com/ThexXTURBOXx/Reforged/blob/1.12/src/main/resources/assets/reforged/textures/items/knife_diamond.png
 - https://github.com/ThexXTURBOXx/Reforged/blob/1.12/src/main/resources/assets/reforged/textures/items/musket_diamond.png

And yes, these are your Reforged textures. Don't be confused!
Balkon's Gets Reforged is a resource pack similar to Reforged Gets Balkon'd - it just replaces the textures from one mod by the textures of the other ones

**Comment by Squeekblach** [comment]
Here you go:

[reforged_netherite.zip](https://github.com/user-attachments/files/16482757/reforged_netherite.zip)

Was that all the necessary ones?

**Comment by ThexXTURBOXx** [comment]
Thank you very much - as always, the textures look great! :)
And yes, these were all the textures I needed!
I have added them to the resource pack and published 1.16.5+ on Modrinth!
Any way I can somehow link you on Modrinth? Do you have a profile there?

**Comment by Squeekblach** [comment]
No problem!
Yep, I am @Squeekblach there as well.

**Comment by ThexXTURBOXx** [comment]
Perfect, thanks! You should have received two invites then
