### ISSUE TITLE
Something with the crash when hovering on the weapons

### ISSUE THREAD

**Issue by ShadowkingREEEE** [ThexXTURBOXx/balkons-weaponmod#42]
Version 1.16.5-1.21.2.jar When looking through JEI or in the Creative tabe to see the name of the weapons crashes the game here is the crash report

[crash-2024-06-28_02.45.19-client.txt](https://github.com/user-attachments/files/16027634/crash-2024-06-28_02.45.19-client.txt)

**Comment by ThexXTURBOXx** [comment]
This is the line where the error occurrs: https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/java/shadows/apotheosis/deadly/affix/AffixEvents.java#L407
I am pretty sure that it is not BWM: Legacy's fault, but rather Apotheosis's.
I will take a closer look later anyway, though. Maybe there is a way to make Apotheosis aware of custom Attributes (it just needs a registry name)
