### ISSUE TITLE
Issue in multiplayer while trying to throw a knife

### ISSUE THREAD

**Issue by vico93** [ThexXTURBOXx/balkons-weaponmod#44]
While trying multiplayer with my friend, when he crafted a stone knife and tried to throw it, while for him the knife flew in the server i didnt see anything and the console was spammed with this errors: https://gist.github.com/vico93/e94a88790a9b00891438849f10fec5ce

MC 1.21, weaponmod-fabric-1.21-1.21.2

**Comment by ThexXTURBOXx** [comment]
This is a known issue of Architectury API: https://github.com/architectury/architectury-api/issues/523
I have already proposed a fix for that, but they need to merge and publish it.
Hence, sadly, there is nothing I can do except telling you to wait for the fix to get published there.

One thing to note: NeoForge works fine - this bug only affects Fabric 1.20.5+

**Comment by vico93** [comment]
Thanks for the clarification
