### ISSUE TITLE
There is a probability of crashing when using Warhammer right-click to attack creatures

### ISSUE THREAD

**Issue by Wheatley11** [ThexXTURBOXx/balkons-weaponmod#45]
version 1.20.1
forge 47.3.1
weaponmod-forge-1.20.1-1.21.3
architectury-9.2.14-forge
cloth-config-11.1.118-forge
There is a probability of crashing when using Warhammer right-click to attack creatures.
I really like this mod.
Also, my English is not good, so I used mechanical translation.

**Comment by Wheatley11** [comment]
I tried to reproduce this bug again and found that it only crashes when the focus is on the creature.
This is the log of the game crash. I hope it can help lock in the bug.
[minecraft-exported-logs-2024-07-01T10-47-35.log](https://github.com/user-attachments/files/16047443/minecraft-exported-logs-2024-07-01T10-47-35.log)

**Comment by ThexXTURBOXx** [comment]
I am trying to reproduce this currently, but I am unable to do so yet.
Your logs are cut-off sadly. Could you try posting the full file?
Also, the file `G:\game\game2\我的世界\.minecraft\versions\1.20.1ff\crash-reports\crash-2024-07-01_10.47.10-client.txt` might help

**Comment by Wheatley11** [comment]
[minecraft-exported-logs-2024-07-01T10-47-35.log](https://github.com/user-attachments/files/16047972/minecraft-exported-logs-2024-07-01T10-47-35.log)

**Comment by Wheatley11** [comment]
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources, file/Minecraft-Mod-Language-Modpack-Converted-1.20.1.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.9, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1547491264 bytes (1475 MiB) / 3254779904 bytes (3104 MiB) up to 8455716864 bytes (8064 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD A8-5600K APU with Radeon(tm) HD Graphics   
	Identifier: AuthenticAMD Family 21 Model 16 Stepping 1
	Microarchitecture: Piledriver
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: AMD Radeon HD 6570
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x6759
	Graphics card #0 versionInfo: DriverVersion=15.201.1151.1008
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 17357.91
	Virtual memory used (MB): 9156.84
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 0.00
	JVM Flags: 11 total; -Xmx8064m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: 1.20.1ff
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon HD 6570 GL version 4.5.13399 Core Profile Forward-Compatible Context 15.201.1151.1008, ATI Technologies Inc.
	Window size: 1440x837
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: file/Minecraft-Mod-Language-Modpack-Converted-1.20.1.zip
	Current Language: zh_cn
	CPU: 4x AMD A8-5600K APU with Radeon(tm) HD Graphics 
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['axieJoy'/652, l='ServerLevel[新的世界]', x=-27.44, y=-60.00, z=22.19]]
	Data Packs: vanilla, mod:mixinextras (incompatible), mod:cloth_config (incompatible), mod:forge, mod:embeddium, mod:embeddiumplus, mod:architectury (incompatible), mod:weaponmod (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.3.1-universal.jar                 |Forge                         |forge                         |47.3.1              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		1[客户端][嵌入]embeddium-0.3.18+mc1.20.1-all.jar       |Embeddium                     |embeddium                     |0.3.18+mc1.20.1     |DONE      |Manifest: NOSIGNATURE
		1[客户端][嵌入++]embeddiumplus-1.20.1-v1.2.12.jar      |Embeddium++                   |embeddiumplus                 |1.2.12              |DONE      |Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |DONE      |Manifest: NOSIGNATURE
		[更多武器]weaponmod-forge-1.20.1-1.21.3.jar           |Balkon's WeaponMod: Legacy    |weaponmod                     |1.21.3              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b69487bf-eeab-43fa-961b-08008832881a
	FML: 47.3
	Forge: net.minecraftforge:47.3.1
[10:47:10] [Render thread/FATAL]: Preparing crash report with UUID d7e09dac-1cc7-481b-872d-fac26a89f091
#@!@# Game crashed! Crash report saved to: #@!@# G:\game\game2\我的世界\.minecraft\versions\1.20.1ff\crash-reports\crash-2024-07-01_10.47.10-client.txt

**Comment by ThexXTURBOXx** [comment]
Sadly, this is still cut off - I need everything that is above `	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}`

Your current crash log does not show something specific to BWM: Legacy yet

**Comment by Wheatley11** [comment]
Sorry, I don't quite understand this. The previous logs were automatically exported by an unofficial launcher. This is the log I found in the logs folder
[latest.log](https://github.com/user-attachments/files/16048385/latest.log)

**Comment by ThexXTURBOXx** [comment]
Now I can see the full crash log, thanks :)

This is the same issue as https://github.com/CyclopsMC/EvilCraft/issues/961, so the fix should be rather analogous
