### ISSUE TITLE
Attack range bonus doesn't work

### ISSUE THREAD

**Issue by MokoBlack** [ThexXTURBOXx/balkons-weaponmod#48]
version:1.12.2 
they just as the same as normal range .

**Comment by ThexXTURBOXx** [comment]
Just tested this again: Works fine on my end! Tested with a stone spear (there is certainly no difference to other spear types, though - as you can see in the video, the sheep is outside the Vanilla attack range as there is no attack indicator, but I can still damage it successfully)

https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy/assets/12763829/0363a129-0e65-4e84-8be8-927b5176584d
