### ISSUE TITLE
[1.7.10] Spear rendering is totally fucked

### ISSUE THREAD

**Issue by Sunconure11** [ThexXTURBOXx/balkons-weaponmod#50]
![image](https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy/assets/5614902/803cbe55-fca6-475b-b940-412ed923e7a8)

**Comment by ThexXTURBOXx** [comment]
Title makes sense lol

**Comment by ThexXTURBOXx** [comment]
Hmmm, I can only sort of reproduce this. In my setup it only looks half as bad as in yours. Are you using some modpack or can you provide me a list of the other mods that are enabled in your setup?

**Comment by ThexXTURBOXx** [comment]
I have fixed it so it looks fine on my machine now. I hope the next update fixes it completely on yours as well!
