### ISSUE TITLE
[SUGGESTION] Increase damage to Warhammer and Battleaxes

### ISSUE THREAD

**Issue by makumaku1974** [ThexXTURBOXx/balkons-weaponmod#51]
At this point, the damages of the weapons are a bit lackluster. Wood and Stone variants is quite understandable but some weapons do need more damage like the battleaxe and warhammer.

Batlleaxes damage starting from stone to diamond should be locked in 8 until netherite it'll be 9.

Warhammer damage starting from stone to diamond should be locked in 7 until netherite it'll be 8.

**Comment by ThexXTURBOXx** [comment]
You are indeed right. This is due to the inofficial 1.12.2 update (which my port is based on) having incorrect values for every melee weapon. I have fixed this now - thanks for reporting! :)
