### ISSUE TITLE
[Balkon's Revised Resourcepack]

### ISSUE THREAD

**Issue by makumaku1974** [ThexXTURBOXx/balkons-weaponmod#52]
[Balkon's Revised.zip](https://github.com/user-attachments/files/16249175/Balkon.s.Revised.zip)

Pre-Release 0.0.1

**Comment by ThexXTURBOXx** [comment]
I have added this to the 1.22.0 milestone -- the only change that this implies is the addition of a link to this issue within the README. Feel free to post updates to this issue even though it is closed. And whenever you want me to change the link, just mention me somehwere (also here if you like to) :)

**Comment by makumaku1974** [comment]
Is this possible to be released on Modrinth so i could constantly update it there? 

How do I mention you in Modrinth?

**Comment by ThexXTURBOXx** [comment]
Of course :)
In that case, I would obviously favour linking the Modrinth entry instead.
If you want to mention me (even though you don't _need_ to), [this is my profile](https://modrinth.com/user/HyperSpeeed)

**Comment by makumaku1974** [comment]
It's kinda required because for dependencies...

**Comment by makumaku1974** [comment]
> Of course :) In that case, I would obviously favour linking the Modrinth entry instead. If you want to mention me (even though you don't _need_ to), [this is my profile](https://modrinth.com/user/HyperSpeeed)

How do I link you as the owner... I got rejected tho for not posting yet in the gallery lol.

**Comment by ThexXTURBOXx** [comment]
That's a good question and tbh, I am not quite sure...
I mean, I (and probably also you) know that there is the "Members" section within the configuration panel of the project and you can add members there.
But I don't know which roles are available there. Just choose one that fits, maybe?

**Comment by ThexXTURBOXx** [comment]
Any news or do you know already what the Modrinth link will be after publication, maybe?

**Comment by ThexXTURBOXx** [comment]
I just noticed that the member system on Modrinth is fundamentally different than the one on CurseForge.
Apparently, one can choose any name as the role for the corresponding member.
In that case, I would suggest something like "Developer" or just "Support" or something like that. All of that does not really fit, but I am also quite unsure what would be an appropriate name.
I still think you really don't _need_ to add me - even though you are of course free to do so :)

**Comment by makumaku1974** [comment]
Sorry for the late reply. I guess its on me to do the uploading. I'll be closing this now.
