### ISSUE TITLE
[ENHANCEMENT] 1.21 Warhammer

### ISSUE THREAD

**Issue by makumaku1974** [ThexXTURBOXx/balkons-weaponmod#53]
WARHAMMER,
Please implement a cooldown meter like from Wind Charge, and Ender Pearls.

**Comment by ThexXTURBOXx** [comment]
The cooldown meter for the Warhammer is a good idea. I will think about possible implications for the Katana, though

**Comment by makumaku1974** [comment]
> The cooldown meter for the Warhammer is a good idea. I will think about possible implications for the Katana, though

Btw, I have posted the resourcepack but still an alpha release due to erm confusion with Basic Weapons.
