### ISSUE TITLE
Addon related question [1.12.2]

### ISSUE THREAD

**Issue by IcarussOne** [ThexXTURBOXx/balkons-weaponmod#55]
I'm currently in progress of an addon for the 1.12.2 version, by registering in the intended method like so, `registry.register(knifeDiamond = WMItemBuilder.createStandardKnife("knife.diamond", ToolMaterial.DIAMOND));` it will end up with the tools being registered under the `weaponmod` mod id rather than the addon's. 

This will result in a lot of `Potentially Dangerous alternative prefix` type errors being spammed on the log without a third party mod fixing that and also confusion from players believing that the supported materials were added by this mod. I was wondering if there could be a custom constructor for API purposes or if there's another way to register the tools without that happening?

**Comment by ThexXTURBOXx** [comment]
Oh, good point. I will add factories that consume a mod ID in the next update :)

**Comment by IcarussOne** [comment]
Awesome! Would be highly appreciated!

**Comment by ThexXTURBOXx** [comment]
The new API has been added in all versions < 1.16.5. For everything >= 1.16.5, it is not needed due to the new `DeferredRegister`s!

**Comment by ThexXTURBOXx** [comment]
I have published 1.22.0 a few hours ago, by the way. I hope that everything works as it should now :)

**Comment by IcarussOne** [comment]
@ThexXTURBOXx
Appreciated! Is there an easy way to set a color for a material that is used in flails and other textures?

**Comment by ThexXTURBOXx** [comment]
Yes, I think I have mentioned it in the README, IIRC.
You need to use the `MaterialRegistry` class for that :)

**Comment by IcarussOne** [comment]
@ThexXTURBOXx
The addon I was working on is now [publicly released](https://www.curseforge.com/minecraft/mc-mods/balkons-expansion)! It is only on 1.12.2 though rather than various versions. :)

**Comment by ThexXTURBOXx** [comment]
Oh, very nice to hear that! Sadly, the last few weeks (even months) have been rather stressful for me, so I wasn't able to work as much on Expanded Armory as I would have liked to. In light of that, it is very nice to see stuff like this from the community! :)

**Comment by IcarussOne** [comment]
> Oh, very nice to hear that! Sadly, the last few weeks (even months) have been rather stressful for me, so I wasn't able to work as much on Expanded Armory as I would have liked to. In light of that, it is very nice to see stuff like this from the community! :)

Hope it gets better! Feel free to also use the textures from my addon if you want to speedup things on Expanded Armory. I only ask for credit in return!
