### ISSUE TITLE
Can You Help Me With Somthing

### ISSUE THREAD

**Issue by Danmccool** [ThexXTURBOXx/balkons-weaponmod#60]
I Am Trying To Build This
[Retro64Mod-1.20.zip](https://github.com/user-attachments/files/16478130/Retro64Mod-1.20.zip)
Can You Please Help

**Comment by ThexXTURBOXx** [comment]
Hello, I am afraid that the zip contains copyrighted material, so I am unable to help, sadly. I am sorry.
