### ISSUE TITLE
1.7.10 Halberd crashes on entity hit

### ISSUE THREAD

**Issue by brandyyn** [ThexXTURBOXx/balkons-weaponmod#62]
[crash-2024-08-05_20.12.05-client.txt](https://github.com/user-attachments/files/16501836/crash-2024-08-05_20.12.05-client.txt)

furthermore, all the bullets apart from the cannon ball don't have recipes?

**Comment by ThexXTURBOXx** [comment]
Thanks for the report, will be fixed in the next update!

**Comment by ThexXTURBOXx** [comment]
As this only concerns 1.7.10, I can already close this

**Comment by brandyyn** [comment]
[crash-2024-08-05_20.14.25-client.txt](https://github.com/user-attachments/files/16502955/crash-2024-08-05_20.14.25-client.txt)
does it also fix this?

**Comment by ThexXTURBOXx** [comment]
That's the same error as before
