### ISSUE TITLE
doesn't work with ExpandedArmory-1.7.10-1.4.1

### ISSUE THREAD

**Issue by brandyyn** [ThexXTURBOXx/balkons-weaponmod#65]
ExpandedArmory-1.7.10-1.4.1 doesn't detect your version of weapon mod 

![image](https://github.com/user-attachments/assets/3dd606bd-ef50-4299-9d3c-e64b5894a7ea)

**Comment by ThexXTURBOXx** [comment]
This is expected and also as things should be.
I have my own fork of Expanded Armory, which will be released rather soon.

**Comment by brandyyn** [comment]
> This is expected and also as things should be. I have my own fork of Expanded Armory, which will be released rather soon.

Good to hear, what integrations have you added or are planning to add?

**Comment by ThexXTURBOXx** [comment]
Related: 
https://github.com/ThexXTURBOXx/Expanded-Armory-Legacy/issues/1 and https://github.com/ThexXTURBOXx/Expanded-Armory-Legacy/issues/2
