### ISSUE TITLE
[Crash] Got a crash with Particular and Blunderbuss.

### ISSUE THREAD

**Issue by makumaku1974** [ThexXTURBOXx/balkons-weaponmod#67]
Was fighting a drowned trident and using a blunderbuss. I had a mod called particular which is a fabric version of effective. This did not have a problem before but somehow it turned into a ticking entity bug. 

![image](https://github.com/user-attachments/assets/1fbe79dc-add2-4afa-bbec-548e02cca67f)

![image](https://github.com/user-attachments/assets/4d1628e0-f92d-458e-86e6-0bc9881897e8)

https://mclo.gs/HwXvzG7 = Log

https://mclo.gs/8aBkplU = Crash Report

**Comment by ThexXTURBOXx** [comment]
Interesting - this even seems like it could affect Vanilla. I will fix this in about 7-10 days when I am finally home again.

**Comment by ThexXTURBOXx** [comment]
The fix now relies on this: https://github.com/Chailotl/particular/pull/41
On BWM: Legacy's side, no fix is needed, actually (and this was a pretty well known issue as indicated by the issue linked above).
The next version of Particular hopefully includes my fix :)

Thanks for reporting this!

Edit: Also, in the meantime, you can disable the water particles in Particular's config as a workaround. This will fix the issue for the time being (setting `waterSplash`).
