### ISSUE TITLE
Mod crashes after hovering over UI 

### ISSUE THREAD

**Issue by BLueIronEye** [ThexXTURBOXx/balkons-weaponmod#68]
Hello, when i hover over the, for example the dagger teh game crashed. When i try crafting it and hover over the itemname it crashes.

i think its a mod problem? I run neoforge 1.21.1

Has anyone an idea or know how to contact the dev? :)

Thank you!

[crash-2024-08-27_05.29.58-client.txt](https://github.com/user-attachments/files/16762068/crash-2024-08-27_05.29.58-client.txt)

**Comment by ThexXTURBOXx** [comment]
If you want to contact me, you are in the right place here :)
This is a known issue and I have reported it (together with a proposed fix) over there: https://github.com/architectury/architectury-api/issues/547

**Comment by BLueIronEye** [comment]
Thank you for answering so fast, how can i implement the changes to fix it myself? i guess i have to mod the mod?

**Comment by ThexXTURBOXx** [comment]
Yeah, you just need to apply the fix I mentioned in the other issue in Architectury API
