### ISSUE TITLE
[fabric 1.19.4] lag problem

### ISSUE THREAD

**Issue by koksu2005** [ThexXTURBOXx/balkons-weaponmod#69]
Whenever i throw a spear or a dagger or a shoot a musket i have a high ping spike even in singleplayer somehow

**Comment by koksu2005** [comment]
and yes i tried other version and it has this problem only on version 1.19.4

**Comment by ThexXTURBOXx** [comment]
I will try to investigate in around 3-4 days

**Comment by koksu2005** [comment]
okay thanks

**Comment by koksu2005** [comment]
i forgot to put that it only happens on big custom maps that weighs 600 mb above

**Comment by ThexXTURBOXx** [comment]
Tried on a 2 GB large map (Oshode City), cannot reproduce. I think you might have other mods installed that could interfere (mixin) into BWM: Legacy's behaviour

**Comment by ThexXTURBOXx** [comment]
Just tried in a rather large modpack, also does not cause lag. I will close this as unreproducible.
