### ISSUE TITLE
[SUGGESTION] Farmer's Delight / BWM Compat

### ISSUE THREAD

**Issue by Thrillville109** [ThexXTURBOXx/balkons-weaponmod#70]
The knife in Farmer's Delight has the same recipe for its knife as BWM, and it gets overwritten by BWM when both are installed. Could it be possible to allow the BWM knife to do the things that it does or allow the FD Knife to replace it if it is installed?

**Comment by ThexXTURBOXx** [comment]
I wouldn't really like to give knives even more abilities. Rather, I suggest to install a mod like [Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph), which will also "fix" every other possible recipe conflict, automatically.
For versions below 1.15.2, there were various mods that did the same thing

**Comment by Thrillville109** [comment]
That is understandable, can you at least make it so that it's called something else if FD is detected? Maybe have it be called a dagger if FD is installed.

**Comment by ThexXTURBOXx** [comment]
Changing item names might confuse players even more since "daggers" are an extra weapon I plan to add (or port from Reforged) at some point.
With a mod like WAILA, HWYLA, or WTHIT, the item tooltips show which mod adds the hovered item, so it is very easy to tell which item is which, I believe.
