### ISSUE TITLE
Hovering the cursor over an item of the balcon causes the game to crash immediately.

### ISSUE THREAD

**Issue by X-Machiavelli** [ThexXTURBOXx/balkons-weaponmod#71]
1. neoforge 21.0.167, MC version 1.21
2. weaponmod-neoforge-1.21-1.22.2.jar
3. architectury-13.0.6-neoforge.jar
4. The launcher runs smoothly.
5. But In game, Hovering the cursor over an item of the balcon causes the game to crash immediately. (forced to exit without an error code) 
6. I have attached the crash report and log here.
[crash-2024-09-14_04.26.17-client.txt](https://github.com/user-attachments/files/16998747/crash-2024-09-14_04.26.17-client.txt)
[latest.log](https://github.com/user-attachments/files/16998749/latest.log)
[debug.log](https://github.com/user-attachments/files/16998750/debug.log)

Thanks for your service.

**Comment by ThexXTURBOXx** [comment]
Same as #68 :)
