### ISSUE TITLE
Game crashes whenever I Access Inventory

### ISSUE THREAD

**Issue by J1Angler** [ThexXTURBOXx/balkons-weaponmod#72]
Title says it all. The game crashes when I click on the combat tab or use the searchbar in Inventory. The problem persists even when I disable all other mods. The "cloth_config" and "architectury" associate mods are the most recent. I'm using the most recent version of 1.21.1 with NeoForge. Attached is my crashlog.
[crash-2024-09-15_19.11.40-client.txt](https://github.com/user-attachments/files/17008171/crash-2024-09-15_19.11.40-client.txt)

**Comment by ThexXTURBOXx** [comment]
Duplicate of #71

**Comment by J1Angler** [comment]
Can you provide me with the edited API?  I can't make the edit.
