### ISSUE TITLE
Reuqesting edited Architectury API for the NeoForge version

### ISSUE THREAD

**Issue by J1Angler** [ThexXTURBOXx/balkons-weaponmod#73]
Hello again.

Based on the comment you provided to my previous request, an edited version of the Architectury API is needed for this mod to work with NeoForge 1.21.1 . I have not been able to make the necessary edit to that API, May you please provide the edited version of the Architectury API so I can run this mod? Based on the comments thread, this is a recurring problem so it would be useful for those who have the same issue and are looking for the fix.

**Comment by ThexXTURBOXx** [comment]
I will not share my version - you can build your own using `gradlew build`. However, this is not a Java nor a Gradle teaching session. Please use Google or some GPT to guide you through the building process.
