### ISSUE TITLE
Add images on modpage to show exactly what the mod adds

### ISSUE THREAD

**Issue by DarthCaesium** [ThexXTURBOXx/balkons-weaponmod#80]
Hi! I would love to use this in my modpack, but I have no idea exactly what it adds. It would be very helpful if you could add more images on the mod's modpage to show what weapons it adds to the game. If it's too much to show, then consider at least adding some more images and making a wiki on the Github page.

**Comment by ThexXTURBOXx** [comment]
Hi! I think, an own Wiki is not really needed as this fantastic Wiki still exists: https://ftbwiki.org/Balkon%27s_WeaponMod
If you click on "Expand" within this table on the page, you can see most of the weapons added by this mod:
![grafik](https://github.com/user-attachments/assets/67dd4eef-27a8-4a98-9973-4ad90fc44dac)

Regarding more images on the mod page: Yes, I might want to do that at some point

**Comment by ThexXTURBOXx** [comment]
Done - added a screenshot of a list of all the weapons to both Modrinth and CurseForge
