### ISSUE TITLE
[Suggestion] Add Better Combat support

### ISSUE THREAD

**Issue by DarthCaesium** [ThexXTURBOXx/balkons-weaponmod#81]
Hi! I'd love to use this in my modpack, but I use Better Combat and it wouldn't work well to add a weapons mod to it if doesn't support Better Combat.

**Comment by ThexXTURBOXx** [comment]
Hi! I am only aware of this incompatibility that I fixed over at Better Combat: https://github.com/ZsoltMolnarrr/BetterCombat/pull/378
But apart from that, everything else should work fine. Please let me know if you find another bug that needs fixing.
