### ISSUE TITLE
Reviving an old Mod

### ISSUE THREAD

**Issue by Blixer200** [ThexXTURBOXx/balkons-weaponmod#82]
maybe this is not the best way to contact the creator of the Balkon's Weapons Mod port as it is a suggestion section, but I would like to see another mod come back to life which was one of the best in 1.7.10 and it would be nice to see it in the current versions, that mod is "Mine & Blade Battlegear 2" I apologize in advance for posting something like this here

**Comment by ThexXTURBOXx** [comment]
I have had more requests about reviving old mods since my BWM:L release. However, sadly, I have to deny all of them because I have not enough time for that. I am very sorry about it.
